services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bookstore-app
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - db
        environment:
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_ADDR=${DB_ADDR}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
        restart: always
        networks:
            - bookstore-network

    db:
        image: mysql:8.0
        container_name: bookstore-db
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - bookstore-network

volumes:
    mysql-data:

networks:
    bookstore-network:
        driver: bridge
